feat: update sbuild to 0.89.3

diff --git a/bin/dobuildlog b/bin/dobuildlog
--- a/bin/dobuildlog
+++ b/bin/dobuildlog
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/sh
 #
 # Copyright © 2002 Rick Younie <rick@def.debian.net>
 #
@@ -31,20 +31,20 @@
 
 # these require setting by the user
 SIGNOPTS='--clearsign --default-key younie@debian.org'
-FROM="$EMAIL"	# "Your Name <your@addr.ess>"
-ARCH=m68k		# for the bug report log link
+FROM="$EMAIL" # "Your Name <your@addr.ess>"
+ARCH=m68k     # for the bug report log link
 
-print_header () {
-    echo "From: $FROM"
-    sed -n '
+print_header() {
+	echo "From: $FROM"
+	sed -n '
 		/^-----/,/^Automatic/ {
 			s/From: /To: /p
 			s/^Subject: Log/Subject: Re: Log/p
 		}'
-    echo
+	echo
 }
 
-fail_options () {
+fail_options() {
 	cat << EOF
 failed
  this one takes a comment,
@@ -64,33 +64,33 @@ upload-rem
 EOF
 }
 
-success_fail () {
-    STATUS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build .*/\1/p')
+success_fail() {
+	STATUS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build .*/\1/p')
 
-    case "$STATUS" in
-	successful )
-	    print_header
-	    sed -n '/\.changes:$/,$ {
+	case "$STATUS" in
+		successful)
+			print_header
+			sed -n '/\.changes:$/,$ {
 				/^Format: /,/^$/p
-			}' |$SIGNPRG 2>/dev/null
-	    ;;
-	failed )
-	    print_header
-	    fail_options
-	    sed -n '/^Automatic build of/,$p'
-	    ;;
-	* )
-	    echo "..this doesn't appear to be a buildd success/fail message"
-	    exit 1
-	    ;;
-    esac
+			}' | $SIGNPRG 2> /dev/null
+			;;
+		failed)
+			print_header
+			fail_options
+			sed -n '/^Automatic build of/,$p'
+			;;
+		*)
+			echo "..this doesn't appear to be a buildd success/fail message"
+			exit 1
+			;;
+	esac
 }
 
-bug_report () {
-    PKG=$1
-    VERS=$2
+bug_report() {
+	PKG=$1
+	VERS=$2
 
-    cat << EOF
+	cat << EOF
 From: $FROM
 To: submit@bugs.debian.org
 Subject: $PKG_VERS: fails to build
@@ -104,8 +104,8 @@ Hi,
 
 EOF
 
-    sed -n '/^Automatic build of/,/^Build needed/ s/^/| /p'
-    cat <<EOF
+	sed -n '/^Automatic build of/,/^Build needed/ s/^/| /p'
+	cat << EOF
 
 
 The $ARCH build logs for $PKG can be found at
@@ -116,17 +116,17 @@ EOF
 }
 
 case "$1" in
-    gpg | agpg )
-	SIGNPRG="$1 $SIGNOPTS"
-	success_fail
-	exit 0
-	;;
-    bug )
-	PKG_VERS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build of \([^ ]*\) .*/\2/p')
-	bug_report $(echo "$PKG_VERS" |sed 's/_/ /')
-	;;
-    * )
-	echo "Usage: $(basename $0) gpg|agpg|bug"
-	exit 1
-	;;
+	gpg | agpg)
+		SIGNPRG="$1 $SIGNOPTS"
+		success_fail
+		exit 0
+		;;
+	bug)
+		PKG_VERS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build of \([^ ]*\) .*/\2/p')
+		bug_report $(echo "$PKG_VERS" | sed 's/_/ /')
+		;;
+	*)
+		echo "Usage: $(basename $0) gpg|agpg|bug"
+		exit 1
+		;;
 esac
diff --git a/debian/tests/unshare b/debian/tests/unshare
--- a/debian/tests/unshare
+++ b/debian/tests/unshare
@@ -9,7 +9,7 @@
 set -exu
 
 if [ -z ${AUTOPKGTEST_TMP+x} ]; then
-	echo "AUTOPKGTEST_TMP is unset" >&2;
+	echo "AUTOPKGTEST_TMP is unset" >&2
 	exit 1
 fi
 
@@ -19,6 +19,12 @@ if [ -z "$release" ]; then
 	exit 1
 fi
 nativearch=$(dpkg --print-architecture)
+# only run the cross-tests on amd64 crossing for arm64 as per
+# https://lists.debian.org/msgid-search/173156754864.3649146.10791472176546387428@localhost
+foreignarch=
+if [ "$nativearch" = amd64 ]; then
+	foreignarch=arm64
+fi
 
 mkdir -p "${AUTOPKGTEST_TMP}/gpghome"
 chmod 700 "${AUTOPKGTEST_TMP}/gpghome"
@@ -26,8 +32,8 @@ export GNUPGHOME="${AUTOPKGTEST_TMP}/gpghome"
 
 verify_orig() {
 	echo "verifying test-pkg_1.0.tar.xz" >&2
-cat << END | base64 -d | xz -cd > "${AUTOPKGTEST_TMP}/expected"
-/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4Cf/BBZdADoZSs4dfiUjFYSOxzYxnd+/m6AlVEVOGf2j
+	cat << END | base64 -d | xz -cd > "${AUTOPKGTEST_TMP}/expected"
+/Td6WFoAAATm1rRGAgAhARwAAAAQz1jM4Cf/BCJdADoZSs4dfiUjFYSOxzYxnd+/m6AlVEVOGf2j
 nT6NK0F9XZ7LLydbY3I//WjMOM2RFpGUqZ8R8Q8lLmydB5SLN5ZQSPW3OJjHlzxVQmv2v3KUyPxo
 V5uvr2rp1j0gfmjB4O+m6SMxUWGmCOp3mrA13iUy99dt9OK9tRQagXItob106li/2LWmOsXR3/5M
 8m/JLF/6KIaYolPsvzut8mTFmik8s22eXjugZufC7CQwXJ7KVb8/LPYgLzHo8tKwkrieBonYFwD+
@@ -41,12 +47,12 @@ evjoP8WJ3fGJfj02LBCQF2Rzp7rOSWjjFfpTaepgIBfuU9BBJ6VecWgsidQ/kJSyL2+ZQ9EFTUET
 YU4/yQ7G+GDJFNij3h0vSuhc2zblAmUvfWNpzZUWORDZhJCIGQnczbbEhzuCILGsnq/8Rw48mMun
 jKxq2HbQrl50uPSnYu94sgaSq9ev3ZXA/ORE9wxzK74nBnurW8KGcUbZyLv0JdBF99d8QdCD50u/
 8JuSVlMB7RBQkH6azuMlObRnPmi1dnUKUwAK3HSSSlxyELIGRgj4dm6BHhtFdTsKDziaNUeE5Cna
-lj7rmf50f/N9LR6HX/+8vtEk7J+R4uLoSlAYi1UUHICfsGeItmOWneGZZ1mEsmhVIRw0YMg1qrgo
-Ngl1nOQuSoqplYrbmxdCw4oduvYB3OgXfcLOcUAc+1WDN5Dmqh6gwxKX8HOm0I38EwPVc9qD0hxR
-Y38ZubJeYl1QScQZndB7mlN5FBaMZTDJfuPbnwykozxXl76gPtZLO2CFcTnL2kvT/40ydjxwXGpA
-hGY9jQZg/RJY+A49vQTPzt87LF8IOdmecD4cNYHyLIOZ8rTlNVWMZ+M7JSu8UhWWGG9jrQ0IVIi9
-HHF+p/1uF4uIAuk/Y8D2ZKB+C3sTI/A47u58/zG6hpHuZbkUJ2qVEIqSBVZhSEuJoaAAAAAAwt/l
-WjS+6mMAAbIIgFAAAOm1wiWxxGf7AgAAAAAEWVo=
+lj7rmf50f/N9LR6HX/+8vtEk7J+R4uLoSlAYi1UUHICfsGeItmOWneGZZ1mEsmhVIRw8IlS17Za9
+weIGkrkKHYm22ZFaXWVcs+o0LIOjgnC5Ku8aQ3cEP3m/owWfpTnTelEw+J7NHqEz70rJVZ8NJUns
+VUeOyzNuZSmDZvMpWJeYZ8uOAqDZ0nUy1HEbZS3HNapbnrUAQQDqU/tPPd9/JkRiPBP0njfdNji9
+UFZAkgO2Z30T7P7oykXf2eNFRZzG76ncklkl+Vzs78q+DL88ET0D2Wo/ewO/w/xiTTKodbVAsW81
+RRSWSLFFaiOQXmfzmIaMNzBPO/f9SoRQbBrzg4X2EEGAefzMnk8TKA+0SlKgv+ya6fN2taUA6dpL
+ePIQMSAAAAAAAygPPa3qIk4AAb4IgFAAAJJ1AFKxxGf7AgAAAAAEWVo=
 END
 	xz -cd < "${AUTOPKGTEST_TMP}/test-pkg_1.0.tar.xz" > "${AUTOPKGTEST_TMP}/test-pkg_1.0.tar"
 	diffoscope "${AUTOPKGTEST_TMP}/expected" "${AUTOPKGTEST_TMP}/test-pkg_1.0.tar"
@@ -58,7 +64,7 @@ verify_deb() {
 	data_tar=$(ar t "${AUTOPKGTEST_TMP}/test-pkg_1.0_all.deb" | grep "^data\.tar\.")
 	case "$data_tar" in
 		data.tar.xz)
-cat << END | base64 -d > "${AUTOPKGTEST_TMP}/expected"
+			cat << END | base64 -d > "${AUTOPKGTEST_TMP}/expected"
 ITxhcmNoPgpkZWJpYW4tYmluYXJ5ICAgMTQ2NzMxMDUxMiAgMCAgICAgMCAgICAgMTAwNjQ0ICA0
 ICAgICAgICAgYAoyLjAKY29udHJvbC50YXIueHogIDE0NjczMTA1MTIgIDAgICAgIDAgICAgIDEw
 MDY0NCAgNDYwICAgICAgIGAK/Td6WFoAAATm1rRGBMCLA4BQIQEWAAAAAAAAABDCPtjgJ/8Bg10A
@@ -77,18 +83,18 @@ gwGAUAAAkAP057HEZ/sCAAAAAARZWg==
 END
 			;;
 		data.tar.zst)
-cat << END | base64 -d > "${AUTOPKGTEST_TMP}/expected"
+			cat << END | base64 -d > "${AUTOPKGTEST_TMP}/expected"
 ITxhcmNoPgpkZWJpYW4tYmluYXJ5ICAgMTQ2NzMxMDUxMiAgMCAgICAgMCAgICAgMTAwNjQ0ICA0
 ICAgICAgICAgYAoyLjAKY29udHJvbC50YXIuenN0IDE0NjczMTA1MTIgIDAgICAgIDAgICAgIDEw
-MDY0NCAgMzUzICAgICAgIGAKKLUv/QBoxQoARhM8I0CJOAcb48sCWwjai6bSHX+FHGgAleqQ7Qv9
-Vh+TxyhuursDNAA0ADEAHbUP6ZSPlgvla0kklqVxGoXCecsNtyGS1bu8fs6O1Wq+FOZ5HEdxmCbx
-MMtSVtM8ykIkAYyDpB2hAROYeBOYLlIpidRAwCPk0nNVFA+xNnR5wN5LrrppO0djAqYkyyG4LrIm
-sOlBHQLbZ9L1kY3nHe0UDhA1LsUV9Qm6ibfxfHQOhLM7blEL2EtqDzG043W8YFPFYMwhbXABiyWN
-vUaoEXKY7axSKl87WS9oX1+U1cvIX1bd8grZ+LitI+qeRt+G7r1THe0BKSCAZsaKFwOHAnO/Y4GM
-gAIBDCtw5x2uGDPaChGsyIVKxs5Sh1w5mIL1OjNKY+M7NlYpw8Jc1gtIDkHYPtptOJOCbkDqDGiw
-1Kjs3OJ4QJM8TXcwWGN/AMn35Y6FJAhTAeaTcwMKZGF0YS50YXIuenN0ICAgIDE0NjczMTA1MTIg
-IDAgICAgIDAgICAgIDEwMDY0NCAgNzcgICAgICAgIGAKKLUv/QBoJQIAlAIuLwAwNzU1ADAAMTI3
-MzUyNjA2Njc3MjAAIDUAdXN0YXIgIAByb290AAogIDH1zwYcBgzI/sCTr+VhgQQwBTCfhBsK
+MDY0NCAgMzUwICAgICAgIGAKKLUv/WQAJ4UKAGaUPR8wr3OfaHLzW/rmP8HOkcTnBovOY5D8n9NV
+ChqKoIoEOAA2ADMAzopgga7cn9jayFtG8+YMBo4DRRCBEMVJW84nYFrPSdtPt2vWoLfmkaQoaqIH
+GkiP05oGQVLTBEwTX2AjUHGM21UqnMGik5ELKa6Yih0Kr5JXEWZU/US5JdyFi3E/Mc36ccPrUYRr
+GOeTnLBSfgS9fL3PvqvOkYV8fzWkHFC5Toxm2C0JLToh31d4Oe4O6auccHGx+cnSkE5IGc7K+nHD
+PQ/NMZB5rpIrR1Zyue+Uq2V6vvq9V991hfscqc3iTh4367dnyayv8/WEYWTqsyWMDyMgoGbE6BwD
+hwLivu4QntW4sszQa2iwIhcqWTtLH3LhYBas18yojQ3csbdKAYvwL9k62jmcZUHtgA22GpVdWRwP
+aJJn6A4Gq+wPmHxdflhYgjAFMJ+wG3l8cGxkYXRhLnRhci56c3QgICAgMTQ2NzMxMDUxMiAgMCAg
+ICAgMCAgICAgMTAwNjQ0ICA3OSAgICAgICAgYAootS/9ZAAnDQIA0sIJEMCnA7Qs/x3bV/QmIfh6
+PwWjUsxVhqCTvrqW2V7Eot1IE/e77AEECSCQmwfPBhwGBrB/kHoYkACmAPOJugHP3myvCg==
 END
 			;;
 		*)
@@ -115,10 +121,21 @@ verify_bin_changes() {
 		"${AUTOPKGTEST_TMP}/test-pkg_1.0_${nativearch}.changes"
 }
 
+verify_foreign_bin_changes() {
+	echo "verifying test-pkg_1.0_${foreignarch}.changes" >&2
+	dscverify --keyring="${AUTOPKGTEST_TMP}/gpghome/pubring.kbx" \
+		"${AUTOPKGTEST_TMP}/test-pkg_1.0_${foreignarch}.changes"
+}
+
 verify_src_changes() {
 	echo "verifying test-pkg_1.0_source.changes" >&2
 	dscverify --keyring="${AUTOPKGTEST_TMP}/gpghome/pubring.kbx" \
 		"${AUTOPKGTEST_TMP}/test-pkg_1.0_source.changes"
+}
+
+verify_commands_log() {
+	echo "verifying absolute path in --pre-build-commands" >&2
+	! grep -v / "${AUTOPKGTEST_TMP}/pre-build-commands.log"
 }
 
 verify() {
@@ -133,46 +150,12 @@ verify() {
 	rm -f "${AUTOPKGTEST_TMP}/test-pkg_1.0_${nativearch}.changes" \
 		"${AUTOPKGTEST_TMP}/test-pkg_1.0_source.changes" \
 		"${AUTOPKGTEST_TMP}/test-pkg_1.0_${nativearch}.buildinfo" \
-		"${AUTOPKGTEST_TMP}/test-pkg_1.0_source.buildinfo"
+		"${AUTOPKGTEST_TMP}/test-pkg_1.0_source.buildinfo" \
+		"${AUTOPKGTEST_TMP}/pre-build-commands.log"
 }
 
-
-# FIXME: generate a key without expiry date
-cat << END | gpg --batch --allow-secret-key-import --import -
------BEGIN PGP PRIVATE KEY BLOCK-----
-
-xVgEYA6+IBYJKwYBBAHaRw8BAQdAM1MKmD3Qm9XwkCv40xOUt1KTLL3nQ2NYfl6B
-n+LOdLMAAQCkkntzWSe/Xsij3RSijtv+SJclZ+8O4p8MzZV66OgabBFOwsARBB8W
-CgCDBYJgDr4gBYkFn6YAAwsJBwkQ8I/4RUH1oMBHFAAAAAAAHgAgc2FsdEBub3Rh
-dGlvbnMuc2VxdW9pYS1wZ3Aub3Jnol5Qc4phlxfxrTOrw9UQlS20xKwlATRTr8Jb
-7ZBPjyoDFQoIApsBAh4BFiEEYTotuR/zjHkQhq+U8I/4RUH1oMAAAAejAP9TNbf+
-KGB7pwj7igR7xB9fag1mW4rS66m6urmHUaxv8wEApQtzmbw2gZDcdR/8k85XfzOE
-iTwx3rJ6dek4INyeSQLNL3NidWlsZCBmYWtlIHVwbG9hZGVyIDxmYWtlLXVwbG9h
-ZGVyQGRlYmlhbi5vcmc+wsAUBBMWCgCGBYJgDr4gBYkFn6YAAwsJBwkQ8I/4RUH1
-oMBHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnF63kQ2as
-sxKVvMSZGTzDgQlwrZMmRnyNf8L57pvR2AUDFQoIApkBApsBAh4BFiEEYTotuR/z
-jHkQhq+U8I/4RUH1oMAAAC9hAQD0DitVEsSsa88L7e53iRtxNUS4ps8K6o5Tp1aX
-8NzjMQEAqD53s2ICMBhQ8J7ub3jMeuthvyImBrdN65/4+gVWxwXHWARgDr4gFgkr
-BgEEAdpHDwEBB0BNjjq4aQ/7iTf/mRfi3Bi2V8hGf5BiDd7D0QkQlNptEwABAIvV
-ziS+mxfuZXfBoT7tjeaiVS0cfnUhiz757pFsp8JREUjCwMgEGBYKAToFgmAOviAF
-iQWfpgAJEPCP+EVB9aDARxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEt
-cGdwLm9yZ8rIdP9aihzTjSrWOpTSuGXz3YmXKV46r4FHEm3IGXTuApsCAh4BvqAE
-GRYKAG8FgmAOviAJEKQXmx3WngHdRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNl
-cXVvaWEtcGdwLm9yZ98fe0i9BRZ7Vha10pZ933EtISKJja+B0Mi+3h+CNHwvFiEE
-/l9vBfi0bJJ8ahzwpBebHdaeAd0AAB+eAP9fO95YdZmmbD0PQ4IExYSbw77eQwM8
-+bRlCb3NnhIlnwD9H1cPlpZlyESBTgYbJ+HiEtIYAfb+j/UYrMLFUEusqAgWIQRh
-Oi25H/OMeRCGr5Twj/hFQfWgwAAA70kBAIMo8zmQnm3dikMTIN1TMq1jL9Scb2eu
-3NTkHwfszJs8AP44F9+fndFRJdHgLABrbz8q2JnBCtJTOjp+I5YcKzhbA8ddBGAO
-viASCisGAQQBl1UBBQEBB0BkyOEsAvMt8QIFlQ2wdC9X5QT/PdTyHgrAT6RZ8mzW
-IAMBCAkAAP9r1GpEGNkv+/S2FNjYRT3YJW04OiTJD+ubMfNHqL9ieBEBwsAJBBgW
-CgB7BYJgDr4gBYkFn6YACRDwj/hFQfWgwEcUAAAAAAAeACBzYWx0QG5vdGF0aW9u
-cy5zZXF1b2lhLXBncC5vcmfFtzHBSr/u6zZM60iohrfYWWunv8HzyxJV7f/9GROX
-fQKbDAIeARYhBGE6Lbkf84x5EIavlPCP+EVB9aDAAAA42AEA2usL+cPAS5/sSTlP
-WPFaWuVIttbR1gVdi/47Ukm2zt4BANsA9OS0U1RVOOylMeZM8O7cI9y+IFCDua9G
-VZd06jMN
-=v7YN
------END PGP PRIVATE KEY BLOCK-----
-END
+sqop generate-key "sbuild fake uploader <fake-uploader@debian.org>" > "${AUTOPKGTEST_TMP}/key.asc"
+gpg --batch --allow-secret-key-import --import - < "${AUTOPKGTEST_TMP}/key.asc"
 
 # Ensure umask is consistent with the blobs above; Debian is already 022 but
 # Ubuntu defaults to 002
@@ -233,7 +216,7 @@ binary-indep: build-indep
 	rm -rf debian/tmp
 	mkdir -p debian/tmp/DEBIAN
 	dpkg-gencontrol
-	dpkg-deb --build debian/tmp ..
+	dpkg-deb --root-owner-group --build debian/tmp ..
 
 binary-arch: build-arch
 
@@ -247,18 +230,32 @@ cat << END > "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/source/format"
 3.0 (native)
 END
 
-mmdebstrap --mode=unshare --variant=apt --skip=cleanup/apt/lists "$release" "${AUTOPKGTEST_TMP}/chroot.tar"
+if ! mmdebstrap --mode=unshare --variant=apt \
+	--include=ca-certificates \
+	--architecture="$nativearch,$foreignarch" \
+	--debug \
+	--hook-dir=/usr/share/mmdebstrap/hooks/copy-host-apt-sources-and-preferences \
+	--hook-dir=/usr/share/mmdebstrap/hooks/file-mirror-automount \
+	--skip=cleanup/apt/lists \
+	"" \
+	"${AUTOPKGTEST_TMP}/chroot.tar"; then
+	echo "Creating chroot with mmdebstrap failed: cannot continue test" >&2
+	exit 77
+fi
 
-env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-buildpackage --build=full
-env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-buildpackage --target=clean
+env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-buildpackage --sign-keyfile="${AUTOPKGTEST_TMP}/key.asc" --build=full
+env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-buildpackage --sign-keyfile="${AUTOPKGTEST_TMP}/key.asc" --target=clean
 verify orig deb dsc bin_changes
 
 run_sbuild() {
-	workingdir=$1; shift
+	workingdir=$1
+	shift
 	env --chdir="${AUTOPKGTEST_TMP}/$workingdir/" sbuild \
 		--no-source-only-changes --nolog \
+		--bd-uninstallable-explainer=apt \
 		--chroot="${AUTOPKGTEST_TMP}/chroot.tar" --chroot-mode=unshare \
 		--keyid="sbuild fake uploader <fake-uploader@debian.org>" \
+		--pre-build-commands="echo %SBUILD_DSC > ${AUTOPKGTEST_TMP}/pre-build-commands.log" \
 		--no-run-lintian --no-run-autopkgtest \
 		--no-apt-upgrade --no-apt-distupgrade --no-apt-update \
 		"$@"
@@ -266,28 +263,42 @@ run_sbuild() {
 
 # Test running sbuild from the unpacked source
 run_sbuild test-pkg-1.0 --source
-verify orig deb dsc bin_changes
+verify orig deb dsc bin_changes commands_log
 
 run_sbuild test-pkg-1.0
-verify orig deb bin_changes
+verify orig deb bin_changes commands_log
+
+# disable cross-builds until #1088971 is fixed in autopkgtest
+if false; then
+	if [ "$nativearch" = amd64 ]; then
+		run_sbuild test-pkg-1.0 --build="$nativearch" --host="$foreignarch" --arch-all
+		verify orig deb foreign_bin_changes
+	fi
+fi
 
 # Test running sbuild on the dsc
 env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-source --build .
 run_sbuild '' --source -d "$release" test-pkg_1.0.dsc
-verify orig deb dsc bin_changes
+verify orig deb dsc bin_changes commands_log
 
 env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-source --build .
-run_sbuild ''  -d "$release" test-pkg_1.0.dsc
-verify orig deb bin_changes
+run_sbuild '' -d "$release" test-pkg_1.0.dsc
+verify orig deb bin_changes commands_log
 
+# Test symlinked .dsc (see https://bugs.debian.org/1012856)
+env --chdir="${AUTOPKGTEST_TMP}/test-pkg-1.0/" dpkg-source --build .
+mv "${AUTOPKGTEST_TMP}/test-pkg_1.0.dsc" "${AUTOPKGTEST_TMP}/test-pkg_1.0_symlink.txt"
+ln -s test-pkg_1.0_symlink.txt "${AUTOPKGTEST_TMP}/test-pkg_1.0.dsc"
+run_sbuild '' -d "$release" test-pkg_1.0.dsc
+verify orig deb bin_changes commands_log
 
 gpgconf --kill all || :
-rm -r -- "${AUTOPKGTEST_TMP}/gpghome/"
+rm -r -- "${AUTOPKGTEST_TMP}/gpghome/" "${AUTOPKGTEST_TMP}/key.asc"
 rm "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/changelog" \
- "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/control" \
- "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/source/format" \
- "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/rules" \
- "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/copyright"
+	"${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/control" \
+	"${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/source/format" \
+	"${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/rules" \
+	"${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/copyright"
 rmdir "${AUTOPKGTEST_TMP}/test-pkg-1.0/debian/source" \
 	"${AUTOPKGTEST_TMP}/test-pkg-1.0/debian" \
 	"${AUTOPKGTEST_TMP}/test-pkg-1.0"
